### ISSUE TITLE
TypeError: Cannot read property 'user' of null

### ISSUE THREAD

**Issue by eth101** [edgraaff/teams-chat-backup#13]
Hi @edgraaff while trying to run this I ran into the error below. It exports all of the chat history into the json files but then stops with that error. Would it be possible to statically define that variable? Otherwise is there anything on my end I can do to fix that? The issue seems to be related to const myId = profile.data.id; but I'm not sure.

TypeError: Cannot read property 'user' of null
    at Backup.createHtml (c:\Users\User\Downloads\teams-chat-backup-master\src\backup.js:180:26)
    at async Backup.run (c:\Users\User\Downloads\teams-chat-backup-master\src\backup.js:36:5)

Thanks,

eth101

**Comment by edgraaff** [comment]
Hi eth101,

Just ago a pull request was merged which should address this issue. Can you update and try again?

Cheers,
Edgar

**Comment by eth101** [comment]
Thanks that solved it!

**Comment by edgraaff** [comment]
Thanks to st-gr :)
